//
//  ProgramEntity.swift
//  44RegattaTimer
//
//  Created by Роман Главацкий on 07.01.2026.
//

import CoreData
import Foundation

// ProgramEntity class is auto-generated by CoreData
// This extension adds custom computed properties

extension ProgramEntity {
    var intervalsArray: [IntervalEntity] {
        let set = intervals as? Set<IntervalEntity> ?? []
        return set.sorted { $0.order < $1.order }
    }
}

